basePath: /
definitions:
  dto.CreateTaskRequest:
    properties:
      description:
        maxLength: 1000
        type: string
      title:
        maxLength: 200
        minLength: 3
        type: string
    required:
    - title
    type: object
  dto.TaskResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
  description: Task service example
  title: Go Tasks API
  version: "1.0"
paths:
  /tasks:
    get:
      description: get tasks with pagination
      parameters:
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.TaskResponse'
            type: array
      summary: List tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: create a new task
      parameters:
      - description: Task data
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.TaskResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create task
      tags:
      - tasks
  /tasks/{id}:
    get:
      description: get task by id
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TaskResponse'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get task
      tags:
      - tasks
swagger: "2.0"
