// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          int32
	Title       string
	Description string
	Done        bool
	CreatedAt   pgtype.Timestamp
}
