// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, description)
VALUES ($1, $2)
RETURNING id, title, description, done, created_at
`

type CreateTaskParams struct {
	Title       string
	Description string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Title, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const createTaskEvent = `-- name: CreateTaskEvent :one
INSERT INTO task_events (task_id, event_type)
VALUES ($1, $2)
RETURNING id, task_id, event_type, created_at
`

type CreateTaskEventParams struct {
	TaskID    int32
	EventType string
}

func (q *Queries) CreateTaskEvent(ctx context.Context, arg CreateTaskEventParams) (TaskEvent, error) {
	row := q.db.QueryRow(ctx, createTaskEvent, arg.TaskID, arg.EventType)
	var i TaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.EventType,
		&i.CreatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, done, created_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, done, created_at FROM tasks ORDER BY id DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Done,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksPaginated = `-- name: ListTasksPaginated :many
SELECT id, title, description, done, created_at
FROM tasks
ORDER BY id DESC
LIMIT $1
OFFSET $2
`

type ListTasksPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTasksPaginated(ctx context.Context, arg ListTasksPaginatedParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Done,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
